### ISSUE TITLE
Conkys have solid backgrounds

### ISSUE THREAD

**Issue by Dobbie03** [ARCHLabs/Archlabs-Other-Config-Files#2]
Since using @erikdubois updated compton config, conky now has a solid grey background.

**Comment by Dobbie03** [comment]
Using the same compton.conf on my main PC without this issue.

**Comment by Dobbie03** [comment]
For some reason Openbox doesn't recognise the compton.conf in ~/.config.  I copied the same file to ~/.config/openbox and restarted the laptop.  Composting now works correctly with COnky.

@osgyan can you include the compton.conf file in the ~/.config/openbox/ folder please.

**Comment by erikdubois** [comment]
anyone else having an issue with the conky's...

**Comment by Dobbie03** [comment]
Like I mentioned above I have fixed my issue, can someone else please let me know if they have this issue?
@toola69 @osgyan

**Comment by erikdubois** [comment]
the start file of openbox is pointing to ~/.config/compton.conf at the moment
compton expects the file to be there.
not keen in having a compton.conf anywhere else
let us figure this out

**Comment by erikdubois** [comment]
`## Compton
## NOTE: composition must be started before tint2
compton -b --config ~/.config/compton.conf &`

**Comment by toola69** [comment]
The compton.conf should be in ~/.config folder @Dobbie03

**Comment by erikdubois** [comment]
solved in 3.3.4
