### ISSUE TITLE
Give all terminals used a beautifull look and feel

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Other-Config-Files#7]
termite in menu
urxvt terminal in menu
xterminal in preferred applications choice

NOT anywhere but installed
lxterminal (keep ? - design?)

give it the same look.
same colouring 
or different
geometry of urxvt bigger, font 1 bigger, colouring ...

**Comment by erikdubois** [comment]
Personal settings
termite : [link](https://github.com/erikdubois/Archlabs-Nemesis/blob/master/personal/680-install-personal-settings-termite-v1.sh)

**Comment by Dobbie03** [comment]
Give all the terminals the same look through out.  Consistency is the key.

**Comment by Dobbie03** [comment]
Do we need lxterminal? I wish we could get the menu commands that require a terminal to work with Termite.  I'd like us to be able to ship just one terminal.

**Comment by erikdubois** [comment]
one is really not enough
you need to have fallbacks
but lxterminal can go

**Comment by Dobbie03** [comment]
Cool, thinking ease of use here, lets swap out URXVT for Terminator too

**Comment by Dobbie03** [comment]
Scratch that, Terminator doesn't like Neofetch

**Comment by erikdubois** [comment]
ok

**Comment by erikdubois** [comment]
do we keep lxterminal? Creating the colour schemes now

**Comment by erikdubois** [comment]
i have uploaded the new colour schemes

**Comment by erikdubois** [comment]
g+ agreed with matt to close
