### ISSUE TITLE
Fonts in menu/header bar too large

### ISSUE THREAD

**Issue by Dobbie03** [ARCHLabs/Archlabs-Other-Config-Files#9]
11pt fonts are too large.  I think these should be 10pt.

**Comment by erikdubois** [comment]
it probably depend on resolution.
is it the menu.xml font itself?

**Comment by erikdubois** [comment]
font 10
![2017-04-22--1492871200_3840x1080_scrot](https://cloud.githubusercontent.com/assets/10594806/25305277/8b9caf7c-2778-11e7-9eac-cd07c21805c1.png)
font 11 
![2017-04-22--1492871285_3840x1080_scrot](https://cloud.githubusercontent.com/assets/10594806/25305286/b08b4d52-2778-11e7-8ab6-047aa804b971.png)
What do others choose?  I am for font 11?

**Comment by erikdubois** [comment]
quite difficult to see... see on you own system guys

**Comment by Dobbie03** [comment]
on my sons laptop, 14" screen, 11pt is too large. 10pt is perfecto.

**Comment by erikdubois** [comment]
it is the font that i used in the screenshots right? the obmenu and titles in it ?

**Comment by Dobbie03** [comment]
Yes obmenu and title bar

**Comment by erikdubois** [comment]
<font place="MenuHeader">
      <name>Noto Sans</name>
      <size>10</size>
      
      <weight>Normal</weight>
      
      <slant>Normal</slant>
      
    </font>
    <font place="MenuItem">
      <name>Noto Sans</name>
      <size>10</size>
      
      <weight>Normal</weight>
      
      <slant>Normal</slant>
      
    </font>

changed

**Comment by erikdubois** [comment]
`  <font place="MenuHeader">
      <name>Noto Sans</name>
      <size>10</size>
      
      <weight>Normal</weight>
      
      <slant>Normal</slant>
      
    </font>
    <font place="MenuItem">
      <name>Noto Sans</name>
      <size>10</size>
      
      <weight>Normal</weight>
      
      <slant>Normal</slant>
      
    </font>`

**Comment by erikdubois** [comment]
font changed from 11 to 10
ok to close ?

**Comment by erikdubois** [comment]
closed with consensus of @Dobbie03
